excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Swagatika123.github.io
title: To follow 
tagline: Keep Moving
description: You can't start the next chapter of your life if you don't want to do so.
paginate: 10